const Report=require("../models/reportModel"),AppError=require("../utils/appError"),catchAsyncErrors=require("../utils/catchAsyncErrors");exports.createReport=catchAsyncErrors((async(r,s,t)=>{const e=await Report.create(r.body);s.status(201).json({message:"success",report:e})})),exports.getAllReport=catchAsyncErrors((async(r,s,t)=>{const e=await Report.find();s.status(200).json({message:"success",results:e.length,data:e})})),exports.updateReportStatus=catchAsyncErrors((async(r,s,t)=>{const{reportId:e,status:o}=r.query,a=await Report.findByIdAndUpdate(e,{status:o},{new:!0,runValidators:!0});a||t(new AppError("No Report found by that report ID",404)),s.status(200).json({message:"success",report:a})}));